---
- name: "Set fact with package list"
  set_fact:
    packages: "{{ app_packages }} + {{ cli_packages }}"

- name: "Update Cache"
  yum: update_cache=yes

- name: "Install packages"
  yum: state=present name={{ item }}
  with_items: "{{ packages }}"
  become: true
