---
- name: "Install  OhMyZShell"
  shell: "curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

 - name: "Adds zsh file"
   copy:
      src: zshrc
      dest: "{{ ansible_env.HOME }}/.zshrc"
      mode: 0640
      owner: "{{ user_name }}"

 - name: Set zsh as default shell
   user: 
      name: "{{ user_name }}"
      shell: /bin/zsh