- hosts: localhost
  tags:
    - always
  tasks:
    - name: "Add target host to ansible memory"
      add_host:
        name: "{{ ip }}"
        groups: myhost
        ansible_user: "{{ user_name }}"
    - name: "Install necessary galaxy roles"
      local_action: command ansible-galaxy install -r requirements.yml

#- hosts: 127.0.0.1
#  connection: local
- hosts: myhost
  vars:
    cli_packages: ['curl', 'wget', 'terraform', 'awscli', 'jenv', 'packer', 'goss', 'virtualbox']
    app_packages: ['google-chrome', 'firefox', 'franz', 'postgres', 'evernote', 'docker', 'spotify', 'dropbox', 'box']
  tasks:
    - import_role:
        name: base
      tags: ['packages']

    - import_role:
        name: shell
      tags: ['shell']

    - import_role:
        name: python
      tags: ['python']

    - import_role:
        name: nodejs
      tags: ['nodejs']

    - import_role:
        name: ssh
      tags: ['ssh']

    - import_role:
        name: git
      tags: ['git']

    - import_role:
        name: vim
      tags: ['vim']
