- hosts: localhost
  tags:
    - always
  tasks:
    - name: "Add target host to ansible memory"
      add_host:
        name: "{{ ip }}"
        groups: myhost
        ansible_user: "{{ user_name }}"
    - name: "Install necessary galaxy roles"
      local_action: command ansible-galaxy install -r requirements.yml

#- hosts: 127.0.0.1
#  connection: local
- hosts: all
  vars:
    cli_packages: ['git', 'zsh', 'ansible', 'awscli', 'curl', 'packer', 'terraform-docs', 'terraform_landscape', 'warrensbox/tap/tfswitch', 'warrensbox/tap/tgswitch', 'kops', 'kubernetes-cli', 'kubernetes-helm', 'go', 'minikube', 'wget', 'openssl', 'ag', 'docker-compose', 'kind' 'k9s', 'kubectx', 'kube-ps1']
    app_packages: ['1password', 'visual-studio-code', 'firefox', 'evernote', 'spotify', 'dropbox', 'virtualbox', 'docker', 'slack', 'notion', 'mongodb-compass']
  tasks:
    - name: "Import Base"
      import_role:
        name: base
      tags: ['packages']

    - name: "Import Shell"
      import_role:
        name: shell
      tags: ['shell']

    - name: "Import Python"
      import_role:
        name: python
      tags: ['python']

    - name: "Import Java"
      import_role:
        name: java
      tags: ['java']

    - name: "Import NodeJS"
      import_role:
        name: nodejs
      tags: ['nodejs']

    - name: "Import SSH"
      import_role:
        name: ssh
      tags: ['ssh']

    - name: "Import Git"
      import_role:
        name: git
      tags: ['git']

    - name: "Import VIM"
      import_role:
        name: vim
      tags: ['vim']
