---
- name: "Set fact with package list"
  set_fact:
    packages: "{{ app_packages }} + {{ cli_packages }}"

- name: "Update cache"
  apt: update_cache=yes

- name: "Install packages"
  apt: state=present name={{ item }}
  with_items: "{{ packages }}"
  become: true
