---
- name: "Install brew"
  shell: "ruby -e '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)' </dev/null"
  args:
    creates: "/usr/local/Cellar"
  become: true
  
- name: "Update brew in case it already exists"
  homebrew:
    update_homebrew: yes
  become: true

- name: "Install packages"
  homebrew: state=present name={{ item }}
  with_items: "{{ base-packages }}"
  become: true

# ---------------------------------
# Install OMZ shell
# ---------------------------------
- include: zsh.yml

# ---------------------------------
# RVM installation
# ---------------------------------
- include: rvm.yml