---
- name: "Update Cache"
  yum: update_cache=yes
  
- name: "Install packages"
  yum: state=present name={{ item }}
  with_items: "{{ base-packages }}"
  become: true

# ---------------------------------
# RVM installation
# ---------------------------------
- include: rvm.yml