---
- name: "Install package in CentOS"
  yum: state=present name=git
  become: true
  when: ansible_os_family == "CentOS"

- name: "Install package in Mac"
  homebrew: state=present name=git
  become: true
  when: ansible_os_family == "MacOSX"

- name: "Install package in Debian"
  apt: state=present name=git
  when: ansible_os_family == "Debian"
