---
- name: "[DGOS] Add repository tap"
  homebrew_tap:
    name: rajatvig/rajat
    state: present

- name: "Install graphical packages"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_mac_app }}"

- name: "Install cli packages"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_mac_cli }}"


