---
- name: "Set fact with package list"
  set_fact:
    cask_packages: "{{ app_packages }} + {{ mac_packages }}"

- name: "[NVM] Creates NVM folder"
  file:
    path: "{{ ansible_env.HOME }}/.nvm"
    state: directory
    mode: 0744

- name: "Install cli packages"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ cli_packages  }}"

- name: "Install graphical packages"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ cask_packages }}"
