---
- name: "Set fact with package list"
  set_fact:
    cask_packages: "{{ app_packages }} + {{ mac_packages }}"

- name: "Inject laptop with caffeine"
  shell: "nohup caffeinate -t 1800 &"

- name: "Install cli packages"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ cli_packages }}"

- name: "Install graphical packages"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ cask_packages }}"
